dist: xenial
language: python
python:
  - 3.8-dev
  - 3.7
  - 3.6
  - 3.5
  - 3.4
  - 3.3
before_install:
  - git clone 'https://github.com/cjlin1/libsvm.git' /opt/libsvm
  - make -C /opt/libsvm
  - make -C /opt/libsvm/python
  - sudo apt-get update -y
  - sudo apt-get install -y libglib2.0-0 libsm6 libfontconfig1 libxrender1
install:
  - pip install -e .[dev]
script:
  - pytest
after_success:
  - bash scripts/deploy.sh
