version: '3.6'

services:
  image-quality:
    image: ocampor/image-quality:${VERSION}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PYTHON_DOCKER_VERSION: 3.7.4-slim
        VERSION: ${VERSION}
