version: '3.6'

services:
  notebook:
    image: ocampor/notebook
    build:
      context: docker/notebook
      dockerfile: Dockerfile
    environment:
      - JUPYTER_PASS=${JUPYTER_PASS}
    ports:
      - 8000:8000
    volumes:
      - ./notebooks:/home/ocampor/notebooks
  image-quality:
    image: ocampor/image-quality:${VERSION}
    build:
      context: .
      dockerfile: docker/test/Dockerfile
      args:
        PYTHON_DOCKER_VERSION: 3.7.4-slim
      target: base
